import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    justifyContent: "flex-start",
  },
  scrollViewContent: {
    alignItems: "center",
    flexGrow: 1,
  },
  restaurantPage: {
    width: '100%',
    alignItems: "center",
    height: '65%',
  },
  topCard: {
    width: "100%",
    height: "25%",
  },
  topCardBackground: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    overflow: "hidden",
  },
  topbar: {
    width: "100%",
    height: "60%",
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    backgroundColor: "lightblue",
  },
  searchbar: {
    width: "70%",
    backgroundColor: "blue",
    top: "70%",
    alignSelf: "center",
  },
  searchtext: {
    color: "white",
    left: "10%",
  },
  greetingText: {
    width: "100%",
    position: "absolute",
    top: "15%",
  },
  hiText: {
    width: "100%",
    textAlign: "center",
    color: "white",
    fontWeight: "bold",
    fontSize: 16,
  },
  name: {
    color: "white",
    fontSize: 15,
  },
  totalPoints: {
    top: "35%",
    color: "gold",
    fontSize: 60,
    fontWeight: "500",
  },
  totalPointsText: {
    top: "35%",
    color: "white",
    fontSize: 14,
  },
  title: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    width: "100%",
    paddingLeft: "6%",
    paddingRight: "10%",
    marginTop: "7%",
    marginBottom: "5%",
  },
  titleText: {
    fontSize: 22,
    fontWeight: "bold",
  },
  viewAll: {
    color: "grey",
    fontSize: 14,
    fontWeight: "400",
    bottom: 3,
  },
  scrollcontainer: {
    width: '100%',
  },
  specialAlign: {
    alignItems: "center",
    justifyContent: "space-evenly",
    height: 150,
    width: "90%",
    flexDirection: "row",
    paddingBottom: 5,
    borderBottomWidth: 1,
    borderColor: "#D3D3D3",
  },
  openButton: {
    height: "90%",
    width: "30%",
  },
  cardContainerShawarma: {
    width: "100%",
    height: "100%",
    borderRadius: 20,
    backgroundColor: "#fff",
  },
  cardContainerShishi: {
    width: "100%",
    height: "100%",
    borderRadius: 20,
    backgroundColor: "#fff",
  },
  cardContainerCrave: {
    width: "100%",
    height: "100%",
    borderRadius: 20,
    backgroundColor: "#fff",
  },
  shawarmaImg: {
    width: "80%",
    height: "50%",
    top: "6%",
    borderRadius: 10,
    alignSelf: "center",
    borderWidth: 1,
    borderColor: "black",
  },
  shishiImg: {
    width: "80%",
    height: "50%",
    top: "6%",
    borderRadius: 10,
    alignSelf: "center",
  },
  craveImg: {
    width: "60%",
    height: "52%",
    alignSelf: "center",
    top: "6%",
    borderRadius: 45,
  },
  restaurantname: {
    fontSize: 15,
    fontWeight: "bold",
    color: "black",
    paddingTop: 10,
    alignItems: "center",
    textAlign: "center",
  },
  emptyRestaurantsText: {
    width: '80%',
    bottom: '4%',
    fontSize: 15,
    fontWeight: "500",
    textAlign: "center",
  },
  pointsCard: {
    fontSize: 12,
    color: "black",
    alignItems: "center",
    textAlign: "center",
  },
  recommendButton: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
    width: "65%",
    height: "5.5%",
    backgroundColor: "#1A6F9E",
    borderRadius: 10,
  },
  recommendText: {
    color: "white",
    fontSize: 16,
  },
  recommendSign: {
    color: "white",
    fontSize: 23,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalContent: {
    backgroundColor: "white",
    padding: 20,
    borderRadius: 10,
    width: "90%",
    alignItems: "center",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    marginTop: 10,
  },
  modalTextInput: {
    width: "90%",
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 25,
    marginBottom: 30,
    marginTop: 25,
    padding: 15,
    paddingStart: 25,
  },
  modalbuttonview: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    width: '100%',
  },
  modalButton: {
    backgroundColor: "#02113F",
    width: "40%",
    padding: 10,
    borderRadius: 30,
    alignItems: "center",
  },
  modalButtonText: {
    color: "white",
    fontSize: 16,
  },
  locationContainer: {
    width: "100%",
    alignItems: "center",
    marginVertical: 10,
  },
  locationButton: {
    height: 40,
    width: "50%",
    backgroundColor: "#02113F",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-evenly",
    borderRadius: 30,
    paddingHorizontal: 10,
    marginBottom: 25,
    marginTop: 15,
  },
  recommendHereText: {
    color: "white",
    fontSize: 13,
    marginTop: 10,
    alignItems: "center",
    paddingHorizontal: 10,
    bottom: 5,
  },
  coordinates: {
    color: "grey",
    width: "90%",
    textAlign: "center",
    marginVertical: 15,
    marginHorizontal: "1%",
    padding: 5,
  },
  loadingContainer1: {
    marginVertical: '25%',
  },
  loadingContainer2: {
    marginVertical: '54%',
  },
});
export default styles;